name: Balto

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Read ruby version
        run: echo ::set-output name=RUBY_VERSION::$(cat test/.ruby-version | cut -f 1,2 -d .)
        id: rv
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{ steps.rv.outputs.RUBY_VERSION }}"
      - uses: ./
        with:
          rootDirectory: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
